version: '3'
services:
  hass:
    image: homeassistant/home-assistant:0.92.1
    env_file: hass.env
    volumes:
      - ./hass:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    ports:
      - "8123:8123"
    networks:
      - hass
    depends_on:
      - mqtt
      - mariadb
      - influxdb
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "-H", "Authorization: Bearer ${HASS_ACCESS_TOKEN}", "http://127.0.0.1:8123/api/"]
      interval: 30s
      timeout: 1s
      retries: 10

  mqtt:
    image: eclipse-mosquitto:1.5.8
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/data
    ports:
      - "1883:1883"
    networks:
      - hass

  samba:
    image: dperson/samba:latest
    networks:
      - samba
    volumes:
      - .:/share
    restart: always
    ports:
      - "139:139"
      - "445:445"
    env_file: samba.env

  duckdns:
    image: meltwater/duckdns:latest
    env_file: duckdns.env
    restart: always

  duplicity:
    image: wernight/duplicity:latest
    env_file: duplicity.env
    user: root
    volumes:
      - .:/data:ro
      - ./duplicity/cache:/home/duplicity/.cache/duplicity
    command:
      - "duplicity"
      - "--full-if-older-than=1M"
      - "--no-encryption"
      - "--allow-source-mismatch"
      - "--s3-use-rrs"
      - "--s3-use-multiprocessing"
      - "--exclude"
      - "/data/unifi-video/data"
      - "--exclude"
      - "/data/duplicity/cache"
      - "/data"
      - "s3://s3.eu-central-1.amazonaws.com/p16-hass-backup/hass"

  hvac-pid:
    build: ./hvac-pid
    env_file: hvac-pid.env
    networks:
      - hass
    restart: always
    depends_on:
      - mqtt
      - hass

  influxdb:
    image: influxdb:1.7.6-alpine
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    networks:
      - hass
    restart: always
    ports:
      - "8086:8086"
    env_file: influxdb.env
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 10

  mqtt-influxdb:
    build: ./mqtt-influxdb
    env_file: ./mqtt-influxdb.env
    networks:
      - hass
    restart: always
    depends_on:
      - mqtt
      - influxdb

  grafana:
    image: grafana/grafana:6.1.4
    env_file: ./grafana.env
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - hass
    restart: always
    depends_on:
      - influxdb

  letsencrypt:
    image: adferrand/letsencrypt-dns:2.5.2
    networks:
      - public
    volumes:
      - ./letsencrypt/domains.conf:/etc/letsencrypt/domains.conf:ro
      - ./letsencrypt/data:/etc/letsencrypt
    env_file: ./letsencrypt.env

  nginx:
    image: nginx:1.16-alpine
    networks:
      - public
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/dhparam.pem:/etc/ssl/dhparam.pem:ro
      - ./letsencrypt/data:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - letsencrypt

  unifi-video:
    image: pducharme/unifi-video-controller:3.10.2
    ports:
      - 1935:1935
      - 6666:6666
      - 7004:7004
      - 7080:7080
      - 7442:7442
      - 7443:7443
      - 7444:7444
      - 7445:7445
      - 7446:7446
      - 7447:7447
      - 10001:10001
    volumes:
      - ./unifi-video/data:/var/lib/unifi-video
      - ./unifi-video/videos:/var/lib/unifi-video/videos
    environment:
      - TZ=Europe/Helsinki
      - DEBUG=1
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    networks:
      - hass

  car-heater-timer:
    build: ./car-heater-timer
    env_file: ./car-heater-timer.env
    networks:
      - hass
    restart: always
    depends_on:
      - hass

  mariadb:
    image: mariadb:10.4
    env_file: ./mariadb.env
    restart: always
    networks: 
      - hass
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 1s
      retries: 10

  oss-scrape:
    build: ./oss-scrape
    env_file: ./oss-scrape.env
    restart: "no"
    networks:
      - hass
    depends_on:
      - influxdb

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.3.1
    restart: always
    networks: 
      - hass
    depends_on:
      - mqtt
    volumes:
      - ./zigbee2mqtt/data:/app/data 
    devices:
      - /dev/ttyACM1:/dev/ttyACM0

volumes:
  mariadb-data:

networks:
  hass:
  samba:
  public:
