- platform: uvc
  nvr: unifi-video
  key: !env_var UNIFI_API_KEY
  password: !env_var UNIFI_CAMERA_PASSWORD
- platform: mjpeg
  name: OctoPrint
  still_image_url: http://octopi.p16.local/webcam/?action=snapshot
  mjpeg_url: http://octopi.p16.local/webcam/?action=stream
