- platform: mqtt
  name: Toshiba Arctic 25
  min_temp: 7
  max_temp: 30
  temp_step: 0.25
  send_if_off: false
  retain: true
  modes:
    - 'off'
    - 'manual'
    - 'heat'
    - 'cool'
  fan_modes:
    - 'auto'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
  current_temperature_topic: "hvac/toshiba-63200289/pid/measured_temperature"
  mode_command_topic: "hvac/toshiba-63200289/pid/mode/set"
  mode_state_topic: "hvac/toshiba-63200289/pid/mode/state"
  temperature_command_topic: "hvac/toshiba-63200289/pid/temperature/set"
  temperature_state_topic: "hvac/toshiba-63200289/pid/temperature/state"
  fan_mode_command_topic: "hvac/toshiba-63200289/pid/fan/set"
  fan_mode_state_topic: "hvac/toshiba-63200289/pid/fan/state"

- platform: generic_thermostat
  name: Office
  heater: switch.office_heating
  target_sensor: sensor.lywsd03mmc_tempc_2
  min_temp: 15
  max_temp: 25
  precision: 0.1
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  min_cycle_duration: 00:01:00
