homeassistant:
  latitude: !env_var HOME_LAT
  longitude: !env_var HOME_LONG
  elevation: 1
  unit_system: metric
  time_zone: Europe/Helsinki
  name: poyta16
  customize: !include customize.yaml

api:
frontend:
history:
sun:
config:
python_script:
system_health:

logbook:
  exclude:
    entities: 
      - automation.heating_update_thermostats

recorder:
  purge_keep_days: 7
  db_url: !env_var MARIADB_HISTORY_URI

lovelace:
  mode: yaml

http:
  api_password: !env_var HA_PASSWORD
  base_url: !env_var HA_BASE_URL
  use_x_forwarded_for: true
  trusted_proxies: "172.0.0.0/8"

mqtt:
  broker: mqtt
  port: 1883
  client_id: hass
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

cast:
  media_player:
  - host: !env_var CHROMECAST_IP

media_player:
  - platform: webostv
    host: !env_var LG_TV_IP

influxdb:
  host: influxdb
  username: !env_var INFLUXDB_USERNAME
  password : !env_var INFLUXDB_PASSWORD
  database : !env_var INFLUXDB_DATABASE

octoprint:
  host: !env_var OCTOPRINT_HOST
  api_key: !env_var OCTOPRINT_KEY

sensor: !include sensor.yaml
switch: !include switch.yaml
climate: !include climate.yaml
zwave: !include zwave.yaml
camera: !include camera.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
weather: !include weather.yaml
notify: !include notify.yaml
automation: !include automation.yaml
