homeassistant:
  latitude: !env_var HOME_LAT
  longitude: !env_var HOME_LONG
  elevation: 1
  unit_system: metric
  time_zone: Europe/Helsinki
  name: poyta16
  customize: !include customize.yaml
  auth_providers:
  - type: legacy_api_password
    api_password: !env_var HA_PASSWORD
  - type: homeassistant

api:
frontend:
history:
sun:
config:
python_script:
system_health:
mobile_app:
webhook:
aurora:

system_log:
  max_entries: 1000

logbook:
  exclude:
    entities:
      - automation.heating_update_thermostats

recorder:
  purge_keep_days: 3
  db_url: !env_var MARIADB_HISTORY_URI

lovelace:
  mode: yaml

http:
  base_url: !env_var HA_BASE_URL
  use_x_forwarded_for: true
  trusted_proxies: "172.0.0.0/8"

mqtt:
  broker: mqtt
  port: 1883
  client_id: hass
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

influxdb:
  host: influxdb
  username: !env_var INFLUXDB_USERNAME
  password : !env_var INFLUXDB_PASSWORD
  database : !env_var INFLUXDB_DATABASE

octoprint:
  host: !env_var OCTOPRINT_HOST
  api_key: !env_var OCTOPRINT_KEY

google:
  client_id: !env_var GOOGLE_CLIENT_ID
  client_secret: !env_var GOOGLE_CLIENT_SECRET

sensor: !include sensor.yaml
switch: !include switch.yaml
climate: !include climate.yaml
zwave: !include zwave.yaml
camera: !include camera.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
# weather: !include weather.yaml
automation: !include automation.yaml
timer: !include timer.yaml
utility_meter: !include utility_meter.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
# scene: !include scene.yaml
input_select: !include input_select.yaml
# device_tracker: !include device_tracker.yaml
person: !include person.yaml
group: !include group.yaml
logger: !include logger.yaml
adaptive_lighting: !include adaptive_lighting.yaml
script: !include script.yaml
# ble_monitor:
#   discovery: false
#   hci_interface:
#     - 2
#     - 3
#   devices:
#     - mac: 'A4:C1:38:70:B0:B6'
#       encryption_key: '516ac6d54db9ac10c9e8ff6efe6cf7b6'
