homeassistant:
  latitude: !env_var HOME_LAT
  longitude: !env_var HOME_LONG
  elevation: 1
  unit_system: metric
  time_zone: Europe/Helsinki
  name: poyta16
  customize: !include customize.yaml

api:
frontend:
history:
logbook:
sun:

http:
  api_password: !env_var HA_PASSWORD
  base_url: !env_var HA_BASE_URL
  use_x_forwarded_for: true
  trusted_proxies: "172.0.0.0/8"

mqtt:
  broker: mqtt
  port: 1883
  client_id: hass

tradfri:
  host: !env_var TRADFRI_HOST
  allow_tradfri_groups: true

cast:
  media_player:
  - host: !env_var CHROMECAST_IP

media_player:
  - platform: webostv
    host: !env_var LG_TV_IP

influxdb:
  host: influxdb
  username: !env_var INFLUXDB_USERNAME
  password : !env_var INFLUXDB_PASSWORD
  database : !env_var INFLUXDB_DATABASE

sensor: !include sensor.yaml
switch: !include switch.yaml
climate: !include climate.yaml
zwave: !include zwave.yaml
camera: !include camera.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
weather: !include weather.yaml
