- platform: mqtt
  name: "Shower room LED strip"
  color_temp: false
  brightness: true
  rgb: false
  schema: json
  command_topic: "zigbee2mqtt/0x00124b001ba6bef4/set"
  state_topic: "zigbee2mqtt/0x00124b001ba6bef4"
  availability_topic: "zigbee2mqtt/0x00124b001ba6bef4/availability"
  json_attributes_topic: "zigbee2mqtt/0x00124b001ba6bef4"

- platform: mqtt
  schema: json
  name: "Shower room downlight"
  command_topic: "zigbee2mqtt/shower_room_downlight/set"
  state_topic: "zigbee2mqtt/shower_room_downlight"
  color_temp: true
  brightness: true
  rgb: false
