# temperature
- platform: mqtt
  state_topic: "ruuvitag/C316F66C57EB"
  name: ruuvitag_indoor_temperature
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature }}'
- platform: mqtt
  state_topic: "ruuvitag/DC136ADEF844"
  name: ruuvitag_outdoor_temperature
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature }}'
- platform: mqtt
  state_topic: "ruuvitag/F53C10BAF234"
  name: ruuvitag_oven_temperature
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature }}'
- platform: mqtt
  state_topic: "bme280/8EB850"
  name: bokashi_temperature
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature }}'
- platform: mqtt
  state_topic: "bme280/8EB9F9"
  name: sauna_temperature
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature }}'

# humidity
- platform: mqtt
  state_topic: "ruuvitag/C316F66C57EB"
  name: ruuvitag_indoor_humidity
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity }}'
- platform: mqtt
  state_topic: "ruuvitag/DC136ADEF844"
  name: ruuvitag_outdoor_humidity
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity }}'
- platform: mqtt
  state_topic: "bme280/8EB9F9"
  name: sauna_humidity
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity }}'

# dew point
- platform: influxdb
  host: influxdb
  username: !env_var INFLUXDB_USERNAME
  password : !env_var INFLUXDB_PASSWORD
  queries:
    - name: ruuvitag_indoor_dewpoint
      unit_of_measurement: °C
      value_template: '{{ value | round(1) }}'
      group_function: last
      where: '"sensor" = ''C316F66C57EB'''
      measurement: environment
      field: dew_point
      database: ruuvitag

# tasmota
- platform: mqtt
  name: garage_side_socket_power
  state_topic: "tele/garage-side-socket/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

- platform: mqtt
  name: garage_front_socket_power
  state_topic: "tele/garage-front-socket/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

# octopi
- platform: template
  sensors:
    octoprint_time_elapsed_format:
      friendly_name: 'Printing Time Elapsed'
      value_template: >-
        {% set etime = states.sensor.octoprint_time_elapsed.state | int %}
        {% set seconds = etime % 60 %}
        {% set minutes = ((etime % 3600) / 60) | int %}
        {% set hours = ((etime % 86400) / 3600) | int %}
        {% set days = (etime / 86400) | int %}
        {%- if days > 0 -%}
          {%- if days == 1 -%}
            1 päivä
          {%- else -%}
            {{ days }} päivää
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 tunti
          {%- else -%}
            {{ hours }} tuntia
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if minutes == 1 -%}
            1 minuutti
          {%- else -%}
            {{ minutes }} minuuttia
          {%- endif -%}
        {%- endif -%}
    octoprint_time_remaining_format:
      friendly_name: 'Printing Time Remaining'
      value_template: >-
        {% set rtime = states.sensor.octoprint_time_remaining.state | int %}
        {% set seconds = rtime % 60 %}
        {% set minutes = ((rtime % 3600) / 60) | int %}
        {% set hours = ((rtime % 86400) / 3600) | int %}
        {% set days = (rtime / 86400) | int %}
        {%- if days > 0 -%}
          {%- if days == 1 -%}
            1 päivä
          {%- else -%}
            {{ days }} päivää
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 tunti
          {%- else -%}
            {{ hours }} tuntia
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if minutes == 1 -%}
            1 minuutti
          {%- else -%}
            {{ minutes }} minuuttia
          {%- endif -%}
        {%- endif -%}

# heatpump pid
- platform: mqtt
  name: heatpump_set_temperature
  state_topic: "hvac/toshiba-63200289/pid/state"
  value_template: '{{ value_json["temperature_set"] }}'
  unit_of_measurement: "°C"
- platform: mqtt
  name: heatpump_fan_speed
  state_topic: "hvac/toshiba-63200289/pid/state"
  value_template: '{{ value_json["fan"] }}'

# Sparsnas
- platform: mqtt
  state_topic: sparsnas/667076
  name: sparsnas_power
  unit_of_measurement: "W"
  value_template: '{{ value_json.Watt | round(1) }}'
  icon: mdi:flash-circle
- platform: mqtt
  state_topic: sparsnas/667076
  name: sparsnas_energy
  unit_of_measurement: "kWh"
  value_template: '{{ value_json.kWh | round(3) }}'
  icon: mdi:flash-circle

# abs humidity
- platform: influxdb
  host: influxdb
  username: !env_var INFLUXDB_USERNAME
  password : !env_var INFLUXDB_PASSWORD
  queries:
    - name: shower_room_absolute_humidity
      unit_of_measurement: g/m³
      value_template: '{{ value | round(2) }}'
      group_function: last
      where: '"sensor" = ''shower_room_temp'''
      measurement: environment
      field: absolute_humidity
      database: agara
- platform: influxdb
  host: influxdb
  username: !env_var INFLUXDB_USERNAME
  password : !env_var INFLUXDB_PASSWORD
  queries:
    - name: indoor_absolute_humidity
      unit_of_measurement: g/m³
      value_template: '{{ value | round(2) }}'
      group_function: last
      where: '"sensor" = ''C316F66C57EB'''
      measurement: environment
      field: absolute_humidity
      database: ruuvitag
- platform: template
  sensors:
    shower_room_moisture:
      friendly_name: "Shower room moisture"
      unit_of_measurement: '%'
      value_template: "{{ ((( states('sensor.shower_room_absolute_humidity')|float - states('sensor.indoor_absolute_humidity')|float) / states('sensor.shower_room_absolute_humidity')|float) * 100) | round(1) }}"

# heatit
- platform: template
  sensors:
    shower_room_floot_set_temperature:
      friendly_name: "Pesuhuoneen lattialämmityksen asetuslämpötila"
      unit_of_measurement: °C
      value_template: "{{ state_attr('climate.thermofloor_as_heatit_thermostat_tf_056_mode', 'temperature')|float }}"

# shelly
- platform: mqtt
  name: "office_heating_power"
  state_topic: "shellies/shelly1pm-76E20A/relay/0/power"
  unit_of_measurement: "W"
- platform: mqtt
  name: "office_heating_temp"
  state_topic: "shellies/shelly1pm-76E20A/temperature"
  unit_of_measurement: "°C"

# ups
- platform: mqtt
  state_topic: "v1/ups/ups/ups.load"
  name: ups_load
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "v1/ups/ups/battery.charge"
  name: ups_battery_charge
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "v1/ups/ups/ups.status"
  name: ups_status
- platform: template
  sensors:
    ups_power:
      unit_of_measurement: W
      value_template: "{{ states('sensor.ups_load')|float * 450 / 100  }}"

# opemqttgateway
- platform: mqtt
  state_topic: 'home/OpenMQTTGateway_ESP32_BLE/BTtoMQTT/A4C13870B0B6'
  name: "mijia_temp_1"
  unit_of_measurement: '°C'
  value_template: '{{ value_json.tem | is_defined }}'
  expire_after: 21600
- platform: mqtt
  state_topic: 'home/OpenMQTTGateway_ESP32_BLE/BTtoMQTT/A4C138BD15EB'
  name: "mijia_temp_2"
  unit_of_measurement: '°C'
  value_template: '{{ value_json.tem | is_defined }}'
  expire_after: 21600
- platform: mqtt
  state_topic: 'home/OpenMQTTGateway_ESP32_BLE/BTtoMQTT/A4C138F8FE1A'
  name: "mijia_temp_3"
  unit_of_measurement: '°C'
  value_template: '{{ value_json.tem | is_defined }}'
  expire_after: 21600

- platform: min_max
  name: indoor_avg
  type: mean
  entity_ids:
    - sensor.ruuvitag_indoor_temperature
    - sensor.0x00158d000346b688_temperature
    - sensor.0x00158d000346b7aa_temperature
    - sensor.0x00158d00036b1ad1_temperature
    - sensor.mijia_temp_1
    - sensor.mijia_temp_2
    - sensor.mijia_temp_3
