- platform: mqtt
  name: car_heater_side
  icon: mdi:power-socket-eu
  state_topic: "stat/garage-side-socket/POWER"
  command_topic: "cmnd/garage-side-socket/POWER"
  availability_topic: "tele/garage-side-socket/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: car_heater_front
  icon: mdi:power-socket-eu
  state_topic: "stat/garage-front-socket/POWER"
  command_topic: "cmnd/garage-front-socket/POWER"
  availability_topic: "tele/garage-front-socket/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: circadian_lighting
  lights_xy:
    - light.shower_room_downlight
    - light.0x90fd9ffffef1731a_light
    - light.0x00124b001d43d764_light
  lights_brightness:
    - light.shower_room_led_strip
    - light.0x90fd9ffffeff2e13_light

- platform: mqtt
  name: "office_heating"
  state_topic: "shellies/shelly1pm-76E20A/relay/0"
  command_topic: "shellies/shelly1pm-76E20A/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  qos: 2
  retain: true
