title: Älytönkoti
views:
- title: Olohuone
  type: vertical-stack
  cards:

  - type: entities
    title: Sisäilma
    entities:
      - sensor.ruuvitag_indoor_temperature
      - sensor.ruuvitag_indoor_humidity
  - type: media-control
    entity: media_player.lg_webos_smart_tv
  - type: media-control
    entity: media_player.televisio

- title: Keittiö
  type: vertical-stack
  cards:
  - type: entities
    title: Ilmalämpöpumppu
    entities:
      - climate.toshiba_arctic_25
  - type: entities
    title: Kahvinkeitin
    entities:
      - sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power
      - sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_energy
      - switch.philio_technology_corporation_pan11_smart_energy_plug_in_switch_switch
  - type: entities
    title: Uuni
    entities:
      - sensor.ruuvitag_oven_temperature

- title: Kodinhoitohuone
  type: vertical-stack
  cards:
  - type: entities
    title: Valaistus
    show_header_toggle: false
    entities:
      - light.kattovalaisin

- title: Piha
  type: vertical-stack
  cards:
  - type: picture-entity
    entity: camera.parkki
    camera_image: camera.parkki
    show_state: false
  - type: picture-entity
    entity: camera.talo
    camera_image: camera.talo
    show_state: false
  - type: entities
    title: Sensorit
    entities:
      - sensor.ruuvitag_outdoor_temperature
      - sensor.ruuvitag_outdoor_humidity
  - type: entities
    title: Katos
    show_header_toggle: false
    entities:
      - switch.car_heater_side
      - sensor.garage_side_socket_power
      - input_boolean.car_heater_side_armed
      - input_datetime.car_heater_side_departure
  - type: entities
    title: Talli
    show_header_toggle: false
    entities:
      - switch.car_heater_front
      - sensor.garage_front_socket_power
      - input_boolean.car_heater_front_armed
      - input_datetime.car_heater_front_departure
  - type: weather-forecast
    entity: weather.darksky
