title: Älytönkoti
resources:
  - url: /local/calendar-card.js?track=true
    type: js
views:
  - id: 0
    title: Yleisnäkymä
    cards:
      - type: sensor
        entity: sensor.indoor_avg
        name: Sisälämpötila
        graph: line
        detail: 2
      - type: sensor
        entity: sensor.ruuvitag_outdoor_temperature
        name: Ulkolämpötila
        graph: line
        detail: 2
      - type: glance
        name: Lämpötila
        entities:
          - entity: sensor.ruuvitag_outdoor_temperature
            name: Ulko
          - entity: sensor.ruuvitag_indoor_temperature
            name: Olohuone
          - entity: sensor.0x00158d000346b688_temperature
            name: Makuuhuone
          - entity: sensor.0x00158d000346b7aa_temperature
            name: Vierashuone
          - entity: sensor.lywsd03mmc_tempc_2
            name: Toimisto
          - entity: sensor.0x00158d00036b1ad1_temperature
            name: Pesuhuone
          - entity: sensor.lywsd03mmc_tempc
            name: eteinen
          - entity: sensor.lywsd03mmc_tempc_3
            name: Kodinhoitohuone
      - type: entities
        title: Paikalla
        show_header_toggle: false
        entities:
          - entity: input_select.occupancy_state
            name: Tila
          - entity: person.jari
            name: Jari
          - entity: person.eppu
            name: Eppu
      - type: entities
        title: Lämmitys
        show_header_toggle: false
        entities:
          - entity: climate.toshiba_arctic_25
            name: Ilmalämpöpumppu
          - entity: climate.thermofloor_as_heatit_thermostat_tf_056_mode
            name: Pesuhuoneen lattialämmitys
      - type: entities
        title: Autojen lämmitys
        show_header_toggle: false
        entities:
          - entity: input_boolean.car_heater_side_armed
            name: Katos ajastettu
          - entity: input_datetime.car_heater_side_departure
            name: Katos lähtöaika
          - type: divider
          - entity: input_boolean.car_heater_front_armed
            name: Talli ajastettu
          - entity: input_datetime.car_heater_front_departure
            name: Talli lähtöaika
      - type: entities
        title: Sähkönkulutus
        show_header_toggle: false
        entities:
          - entity: sensor.sparsnas_power
            name: Teho
          - entity: sensor.electricity_daily
            name: Sähkönkulutus tänään
          - entity: sensor.electricity_monthly
            name: Sähkönkulutus tässä kuussa
      - type: custom:calendar-card
        title: "Kalenteri"
        progressBar: true
        showMultiDay: true
        numberOfDays: 30
        showLocation: true
        entities:
        - calendar.yhteinen

  - id: 1
    title: Olohuone
    cards:
      - id: 42a847cb69ef4a2faf15942309522c0f
        type: entities
        title: Sisäilma
        show_header_toggle: false
        entities:
          - sensor.ruuvitag_indoor_temperature
          - sensor.ruuvitag_indoor_humidity
          - entity: sensor.ruuvitag_indoor_dewpoint
            name: Sisäilman kastepiste
            icon: mdi:water
      - type: media-control
        entity: media_player.living_room_tv

  - id: 2
    title: Keittiö
    cards:
      - id: 0101005e8a7c412b83b1b00e4736a8a9
        type: entities
        title: Ilmalämpöpumppu
        show_header_toggle: false
        entities:
          - entity: climate.toshiba_arctic_25
            icon: mdi:thermostat
          - entity: sensor.heatpump_set_temperature
            name: Asetuslämpötila
          - entity: sensor.heatpump_fan_speed
            name: Puhallus
            icon: mdi:fan
          - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power
            icon: mdi:gauge
          - entity: sensor.hvac_energy_daily
            name: Energiankulutus tänään
            icon: mdi:power-plug
          - entity: sensor.hvac_energy_monthly
            name: Energiankulutus tämä kk
            icon: mdi:power-plug
      - type: history-graph
        title: 'Ilmalämpöpumppu teho'
        refresh_interval: 60
        entities:
          - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power
            name: Teho
      - type: entities
        title: Uuni
        show_header_toggle: false
        entities:
          - sensor.ruuvitag_oven_temperature
      - type: history-graph
        title: Lämpötila
        refresh_interval: 60
        entities:
          - entity: sensor.ruuvitag_oven_temperature
            name: Uuni
          - entity: sensor.ruuvitag_indoor_temperature
            name: Ilma
      - type: entities
        title: Kahvinkeitin
        show_header_toggle: false
        entities:
          - entity: switch.0x000d6ffffee3cb28
            name: Virtapistoke
  - id: 3
    title: Kodinhoitohuone
    cards:
      - type: sensor
        entity: sensor.lywsd03mmc_tempc_3
        name: Lämpötila
        graph: line
        detail: 2
      - type: light
        entity: light.0x90fd9ffffef1731a
        name: Kattovalaisin
      - type: light
        entity: light.0x00124b001d43d764
        name: LED-nauha
      - type: entities
        entities:
          - entity: binary_sensor.shelly1_2c6915
            name: Valokatkaisija
          - entity: binary_sensor.0x00158d00034ce398_occupancy
            name: Liiketunnistin

  - title: Eteinen
    cards:
      - type: sensor
        entity: sensor.lywsd03mmc_tempc
        name: Lämpötila
        graph: line
        detail: 2
      - type: light
        entity: light.0x90fd9ffffeff2e13_light
      - type: entities
        title: Valaistus
        show_header_toggle: false
        entities:
          - entity: binary_sensor.0xd0cf5efffe124b79_occupancy
            secondary_info: last-updated
          - entity: sensor.0xd0cf5efffe124b79_battery
            secondary_info: last-updated

  - title: Pesuhuone/sauna
    cards:
      - type: history-graph
        refresh_interval: 60
        title: Lämpötila
        entities:
          - entity: sensor.0x00158d00036b1ad1_temperature
            name: Ilma
          - entity: sensor.thermofloor_as_heatit_thermostat_tf_033_external_sensor
            name: Lattia
      - type: entities
        title: Mittaus
        show_header_toggle: false
        entities:
          - entity: sensor.0x00158d00036b1ad1_temperature
            name: Pesuhuone lämpötila
          - entity: sensor.thermofloor_as_heatit_thermostat_tf_033_external_sensor
            name: Pesuhuoneen lattian lämpötila
          - entity: sensor.0x00158d00036b1ad1_humidity
            name: Pesuhuone ilmankosteus
      - type: gauge
        name: Pesuhuoneen kosteustaso
        unit: '%'
        entity: sensor.shower_room_moisture
        min: 0
        max: 100
        severity:
          green: 10
          yellow: 20
          red: 30
      - type: entities
        title: Lämmitys
        show_header_toggle: false
        entities:
          - type: conditional
            conditions:
              - entity: timer.shower_room_manual_heating
                state: active
            row:
              entity: timer.shower_room_manual_heating
              name: Automatiikan ohitusta jäljellä
          - type: conditional
            conditions:
              - entity: timer.shower_room_manual_heating
                state: active
            row:
              entity: script.cancel_shower_room_manual_heating
              name: Automatiikan ohitus
              icon: mdi:alarm-off
              action_name: Peruuta
          - type: conditional
            conditions:
              - entity: timer.shower_room_manual_heating
                state_not: active
            row:
              entity: script.start_shower_room_manual_heating
              name: Automatiikan ohitus
              icon: mdi:alarm
              action_name: Aloita
          - entity: climate.thermofloor_as_heatit_thermostat_tf_056_mode
          - name: Lattialämmityksen asetuslämpötila
            entity: sensor.shower_room_floot_set_temperature
          - name: Teho
            icon: mdi:flash
            entity: sensor.thermofloor_as_heatit_thermostat_tf_033_power

      - type: entities
        title: Alasvalot
        show_header_toggle: false
        entities:
        - entity: light.shower_room_downlight
          name: Valot
        - entity: binary_sensor.shelly1_25a447
          name: Painike
      - type: entities
        title: LED lista
        show_header_toggle: false
        entities:
        - entity: light.0x00124b001ba6bef4_light
          name: Valot
        - entity: binary_sensor.shelly1_25abb7
          name: Painike

  - title: Toimisto
    cards:
      - type: sensor
        entity: sensor.lywsd03mmc_tempc_2
        name: Lämpötila
        graph: line
        detail: 2
      - type: thermostat
        entity: climate.office_2
      - type: entities
        title: Lämmitys
        show_header_toggle: false
        entities:
          - entity: sensor.office_heating_power
            name: Teho
      - type: entities
        title: 3D tulostin
        show_header_toggle: false
        entities:
          - entity: switch.0x000d6ffffedaafbf
            name: Virtakytkin
          - sensor.octoprint_current_state
          - sensor.octoprint_job_percentage
          - sensor.octoprint_time_elapsed_format
          - sensor.octoprint_time_remaining_format
          - type: divider
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_actual_tool0_temp

  - id: 4
    title: Piha
    #type: vertical-stack
    cards:
      - id: 43406de7cd1f4f129ad6a89ab083cdb3
        type: picture-entity
        entity: camera.parkki
        camera_image: camera.parkki
        show_state: false
      - id: f24d163ee0d245ce90b4c9d40a52582c
        type: picture-entity
        entity: camera.talo
        camera_image: camera.talo
        show_state: false
      - id: fddc994c5f7a4924aca65a3f076ebb27
        type: entities
        title: Mittaus
        show_header_toggle: false
        entities:
          - sensor.ruuvitag_outdoor_temperature
          - sensor.ruuvitag_outdoor_humidity
      - id: 2feb1de222484885b495af3e49a7af41
        type: entities
        title: Katos
        show_header_toggle: false
        entities:
          - entity: switch.car_heater_side
            secondary_info: last-changed
          - sensor.garage_side_socket_power
          - input_boolean.car_heater_side_armed
          - input_datetime.car_heater_side_departure
      - id: 343308fb27034491aa6db427c9bd2b80
        type: entities
        title: Talli
        show_header_toggle: false
        entities:
          - entity: switch.car_heater_front
            secondary_info: last-changed
          - sensor.garage_front_socket_power
          - input_boolean.car_heater_front_armed
          - input_datetime.car_heater_front_departure
