title: Älytönkoti
resources:
  - url: /local/calendar-card.js?track=true
    type: js
  - url: /local/zigbee2mqtt-networkmap.js?v=0.6.0
    type: module
views:
  - id: 0  # Automatically created id
    title: Yleisnäkymä
    type: horizontal-stack
    cards:
      - type: history-graph
        title: Lämpötila
        refresh_interval: 60
        entities:
          - entity: sensor.ruuvitag_indoor_temperature
            name: Sisällä
          - entity: sensor.ruuvitag_outdoor_temperature
            name: Ulkona
      - type: glance
        name: Lämpötila
        entities:
          - sensor.ruuvitag_outdoor_temperature
          - sensor.ruuvitag_indoor_temperature
          - sensor.0x00158d000346b688_temperature
          - sensor.0x00158d000346b7aa_temperature
          - sensor.0x00158d00036b1ad1_temperature
      - type: entities
        title: Paikalla
        show_header_toggle: false
        entities:
          - entity: input_select.occupancy_state
            name: Tila
          - entity: person.jari
            name: Jari
          - entity: person.eppu
            name: Eppu
      - type: entities
        title: Lämmitys
        show_header_toggle: false
        entities:
          - climate.toshiba_arctic_25
          - climate.thermofloor_as_heatit_thermostat_tf_056_mode
          - climate.guestroom
          - climate.bedroom
      - type: entities
        title: Autojen lämmitys
        show_header_toggle: false
        entities:
          - entity: input_boolean.car_heater_side_armed
            name: Katos ajastettu
          - entity: input_datetime.car_heater_side_departure
            name: Katos lähtöaika
          - type: divider
          - entity: input_boolean.car_heater_front_armed
            name: Talli ajastettu
          - entity: input_datetime.car_heater_front_departure
            name: Talli lähtöaika
      - type: entities
        title: Sähkönkulutus
        show_header_toggle: false
        entities:
          - entity: sensor.sparsnas_power
            name: Teho
          - entity: sensor.electricity_daily
            name: Sähkönkulutus tänään
          - entity: sensor.electricity_monthly
            name: Sähkönkulutus tässä kuussa
      - type: custom:calendar-card
        title: "Kalenteri"
        progressBar: true
        showMultiDay: true
        numberOfDays: 30
        showLocation: true
        entities:
        - calendar.yhteinen

  - id: 1  # Automatically created id
    title: Olohuone
    type: vertical-stack
    cards:
      - id: 42a847cb69ef4a2faf15942309522c0f  # Automatically created id
        type: entities
        title: Sisäilma
        show_header_toggle: false
        entities:
          - sensor.ruuvitag_indoor_temperature
          - sensor.ruuvitag_indoor_humidity
          - entity: sensor.ruuvitag_indoor_dewpoint
            name: Sisäilman kastepiste
            icon: mdi:water
      - type: media-control
        entity: media_player.lg_webos_smart_tv
      - type: media-control
        entity: media_player.living_room_tv

  - id: 2  # Automatically created id
    title: Keittiö
    type: vertical-stack
    cards:
      - id: 0101005e8a7c412b83b1b00e4736a8a9  # Automatically created id
        type: entities
        title: Ilmalämpöpumppu
        show_header_toggle: false
        entities:
          - entity: climate.toshiba_arctic_25
            icon: mdi:thermostat
          - entity: sensor.heatpump_set_temperature
            name: Asetuslämpötila
          - entity: sensor.heatpump_fan_speed
            name: Puhallus
            icon: mdi:fan
          - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power
            icon: mdi:gauge
          - entity: sensor.hvac_energy_daily
            name: Energiankulutus tänään
            icon: mdi:power-plug
          - entity: sensor.hvac_energy_monthly
            name: Energiankulutus tämä kk
            icon: mdi:power-plug
      - type: history-graph
        title: 'Ilmalämpöpumppu teho'
        refresh_interval: 60
        entities:
          - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power
            name: Teho
      - type: entities
        title: Uuni
        show_header_toggle: false
        entities:
          - sensor.ruuvitag_oven_temperature
      - type: history-graph
        title: Lämpötila
        refresh_interval: 60
        entities:
          - entity: sensor.ruuvitag_oven_temperature
            name: Uuni
          - entity: sensor.ruuvitag_indoor_temperature
            name: Ilma
      - type: entities
        title: Kahvinkeitin
        show_header_toggle: false
        entities:
          - entity: switch.0x000d6ffffee3cb28_switch
            name: Virtapistoke
  - id: 3  # Automatically created id
    title: Kodinhoitohuone
    type: vertical-stack
    cards:
      - type: light
        entity: light.0x90fd9ffffef1731a_light
        name: Kattovalaisin
      - type: light
        entity: light.0x00124b001d43d764_light
        name: LED-nauha
      - type: entities
        entities:
          - entity: binary_sensor.shelly1_2c6915
            name: Valokatkaisija
          - entity: binary_sensor.0x00158d00034ce398_occupancy
            name: Liiketunnistin

  - title: Eteinen
    type: vertical-stack
    cards:
      - type: light
        entity: light.0x90fd9ffffeff2e13_light
      - type: entities
        title: Valaistus
        show_header_toggle: false
        entities:
          - binary_sensor.0xd0cf5efffe124b79_occupancy
          - sensor.0xd0cf5efffe124b79_battery

  - title: Pesuhuone/sauna
    type: vertical-stack
    cards:
      - type: history-graph
        title: Lämpötila
        entities:
          - entity: sensor.0x00158d00036b1ad1_temperature
            name: Ilma
          - entity: sensor.thermofloor_as_heatit_thermostat_tf_033_external_sensor
            name: Lattia
      - type: entities
        title: Mittaus
        show_header_toggle: false
        entities:
          - entity: sensor.0x00158d00036b1ad1_temperature
            name: Pesuhuone lämpötila
          - entity: sensor.thermofloor_as_heatit_thermostat_tf_033_external_sensor
            name: Pesuhuoneen lattian lämpötila
          - entity: sensor.0x00158d00036b1ad1_humidity
            name: Pesuhuone ilmankosteus
      - type: gauge
        name: Pesuhuoneen kosteustaso
        unit: '%'
        entity: sensor.shower_room_moisture
        min: 0
        max: 100
        severity:
          green: 10
          yellow: 20
          red: 30
      - type: entities
        title: Lämmitys
        show_header_toggle: false
        entities:
          - entity: climate.thermofloor_as_heatit_thermostat_tf_056_mode
          - name: Lattialämmityksen asetuslämpötila
            entity: sensor.shower_room_floot_set_temperature 
          - name: Teho
            icon: mdi:flash
            entity: sensor.thermofloor_as_heatit_thermostat_tf_033_power
      - type: entities
        title: Alasvalot
        show_header_toggle: false
        entities:
        - entity: light.shower_room_downlight
          name: Valot
        - entity: binary_sensor.shelly1_25a447
          name: Painike
      - type: entities
        title: LED lista
        show_header_toggle: false
        entities:
        - entity: light.shower_room_led_strip
          name: Valot
        - entity: binary_sensor.shelly1_25abb7
          name: Painike

  - title: Toimisto
    type: vertical-stack
    cards:
      - type: entities
        title: Lämmitys
        show_header_toggle: false
        entities:
          - entity: switch.office_heating
            name: Lämmitys päällä
          - entity: sensor.office_heating_power
            name: Teho
      - type: picture-entity
        entity: camera.octoprint
        camera_image: camera.octoprint
        show_state: false
        show_name: false
        aspect_ratio: 4x3
      - type: entities
        title: 3D tulostin
        show_header_toggle: false
        entities:
          - entity: switch.0x000d6ffffedaafbf_switch
            name: Virtakytkin
          - sensor.octoprint_current_state
          - sensor.octoprint_job_percentage
          - sensor.octoprint_time_elapsed_format
          - sensor.octoprint_time_remaining_format
          - type: divider
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_actual_tool0_temp

  - id: 4  # Automatically created id
    title: Piha
    type: vertical-stack
    cards:
      - id: 43406de7cd1f4f129ad6a89ab083cdb3  # Automatically created id
        type: picture-entity
        entity: camera.parkki
        camera_image: camera.parkki
        show_state: false
      - id: f24d163ee0d245ce90b4c9d40a52582c  # Automatically created id
        type: picture-entity
        entity: camera.talo
        camera_image: camera.talo
        show_state: false
      - id: fddc994c5f7a4924aca65a3f076ebb27  # Automatically created id
        type: entities
        title: Mittaus
        show_header_toggle: false
        entities:
          - sensor.ruuvitag_outdoor_temperature
          - sensor.ruuvitag_outdoor_humidity
      - id: 2feb1de222484885b495af3e49a7af41  # Automatically created id
        type: entities
        title: Katos
        show_header_toggle: false
        entities:
          - entity: switch.car_heater_side
            secondary_info: last-changed
          - sensor.garage_side_socket_power
          - input_boolean.car_heater_side_armed
          - input_datetime.car_heater_side_departure
      - id: 343308fb27034491aa6db427c9bd2b80  # Automatically created id
        type: entities
        title: Talli
        show_header_toggle: false
        entities:
          - entity: switch.car_heater_front
            secondary_info: last-changed
          - sensor.garage_front_socket_power
          - input_boolean.car_heater_front_armed
          - input_datetime.car_heater_front_departure
      - id: 0c3c88a2880a4715a132600ac0d4d274  # Automatically created id
        type: weather-forecast
        entity: weather.darksky
  - title: Zigbee Network
    panel: true # this renders the first card on full width, other cards in this view will not be rendered
    cards:
      - type: custom:zigbee2mqtt-networkmap
        entity: sensor.zigbee2mqtt_networkmap
        # the following are optional:
        mqtt_base_topic: zigbee2mqtt # if you change base_topic of Zigbee2mqtt, change it accordingly
        force: 3000 # decrease it to get smaller map if you have many devices
        node_size: 16
        font_size: 12
        link_width: 2
        height: 800 # height of the card
        # use this css config or use whatever css tech to change look and feel,
        # the same variable can also be used in Home Assistant themes, see https://www.home-assistant.io/components/frontend/#defining-themes
        css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(18, 120, 98, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #dcfaf3;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(18, 120, 98, .5);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #127862;
            --zigbee2mqtt-networkmap-arrow-color: rgba(18, 120, 98, 0.7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
          }