title: Älytönkoti
resources:
  - url: /local/calendar-card.js?track=true
    type: js
views:
  - id: 0  # Automatically created id
    title: Yleisnäkymä
    type: horizontal-stack
    cards:
      - type: history-graph
        title: Lämpötila
        refresh_interval: 60
        entities:
          - entity: sensor.ruuvitag_indoor_temperature
            name: Sisällä
          - entity: sensor.ruuvitag_outdoor_temperature
            name: Ulkona
          - entity: sensor.sauna_temperature
            name: Sauna
      - type: glance
        name: Lämpötila
        entities:
          - sensor.ruuvitag_indoor_temperature
          - sensor.sauna_temperature
          - sensor.ruuvitag_outdoor_temperature
          - sensor.thermofloor_as_heatit_thermostat_tf_033_external_sensor
          - sensor.0x00158d000346b688_temperature
          - sensor.0x00158d00036b1ad1_temperature
          - sensor.0x00158d000346b7aa_temperature
      - id: 98b65816120241278d23ab4da355fba6  # Automatically created id
        type: entities
        title: Lämmitys
        show_header_toggle: false
        entities:
          - climate.toshiba_arctic_25
          - climate.thermofloor_as_heatit_thermostat_tf_033_heating

      - id: f354c9aed2b94f1884cda099bbec4a5f  # Automatically created id
        type: entities
        title: Autojen lämmitys
        show_header_toggle: false
        entities:
          - entity: input_boolean.car_heater_side_armed
            name: Katos ajastettu
          - entity: input_datetime.car_heater_side_departure
            name: Katos lähtöaika
          - type: divider
          - entity: input_boolean.car_heater_front_armed
            name: Talli ajastettu
          - entity: input_datetime.car_heater_front_departure
            name: Talli lähtöaika
      - type: entities
        title: Sähkönkulutus
        show_header_toggle: false
        entities:
          - entity: sensor.sparsnas_power
            name: Teho
          - entity: sensor.electricity_daily
            name: Sähkönkulutus tänään
          - entity: sensor.electricity_monthly
            name: Sähkönkulutus tässä kuussa
      - type: custom:calendar-card
        title: "Kalenteri"
        progressBar: true
        showMultiDay: true
        numberOfDays: 30
        showLocation: true
        entities:
        - calendar.yhteinen

  - id: 1  # Automatically created id
    title: Olohuone
    type: vertical-stack
    cards:
      - id: 42a847cb69ef4a2faf15942309522c0f  # Automatically created id
        type: entities
        title: Sisäilma
        show_header_toggle: false
        entities:
          - sensor.ruuvitag_indoor_temperature
          - sensor.ruuvitag_indoor_humidity
          - entity: sensor.ruuvitag_indoor_dewpoint
            name: Sisäilman kastepiste
            icon: mdi:water
      - id: 47bee9e503b74553b1307101c129ddaf  # Automatically created id
        type: media-control
        entity: media_player.lg_webos_smart_tv
      - id: 5b260acfb42141d0aaa3d81f98c811d9  # Automatically created id
        type: media-control
        entity: media_player.televisio

  - id: 2  # Automatically created id
    title: Keittiö
    type: vertical-stack
    cards:
      - id: 0101005e8a7c412b83b1b00e4736a8a9  # Automatically created id
        type: entities
        title: Ilmalämpöpumppu
        show_header_toggle: false
        entities:
          - entity: climate.toshiba_arctic_25
            icon: mdi:thermostat
          - entity: sensor.heatpump_set_temperature
            name: Asetuslämpötila
          - entity: sensor.heatpump_fan_speed
            name: Puhallus
            icon: mdi:fan
          - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power
            icon: mdi:gauge
          - entity: sensor.hvac_energy_daily
            name: Energiankulutus tänään
            icon: mdi:power-plug
          - entity: sensor.hvac_energy_monthly
            name: Energiankulutus tämä kk
            icon: mdi:power-plug
      - type: history-graph
        title: 'Ilmalämpöpumppu teho'
        entities:
          - entity: sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power
            name: Teho
      - id: fcb460d001534433b44e076429b8d81a  # Automatically created id
        type: entities
        title: Uuni
        show_header_toggle: false
        entities:
          - sensor.ruuvitag_oven_temperature
      # - id: 2e8e396edcb14e66a440608fc74a9087  # Automatically created id
      #   type: thermostat
      #   entity: climate.toshiba_arctic_25
      - type: entities
        title: Bokashi
        show_header_toggle: false
        entities:
          - entity: sensor.bokashi_temperature
            name: Sankon lämpötila
  - id: 3  # Automatically created id
    title: Kodinhoitohuone
    type: vertical-stack
    cards:
      - type: light
        entity: light.0x90fd9ffffef1731a_light

  - title: Eteinen
    type: vertical-stack
    cards:
      - type: light
        entity: light.0x90fd9ffffeff2e13_light
      - type: entities
        title: Valaistus
        show_header_toggle: false
        entities:
          - binary_sensor.0xd0cf5efffe124b79_occupancy
          - sensor.0xd0cf5efffe124b79_battery

  - title: Pesuhuone/sauna
    type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.sauna_temperature
            name: Sauna lämpötila
          - entity: sensor.sauna_humidity
            name: Sauna ilmankosteus
      - type: entities
        show_header_toggle: false
        entities:
          - entity: climate.thermofloor_as_heatit_thermostat_tf_033_heating
          - name: Teho
            icon: mdi:flash
            entity: sensor.thermofloor_as_heatit_thermostat_tf_033_power
          - name: Lämmitä 60 min
            entity: input_boolean.bathroom_force_heat
      - type: light
        entity: light.0xd0cf5efffe1e8eb9_light
      - type: light
        entity: light.0xd0cf5efffe1e963f_light

  - title: Toimisto
    type: vertical-stack
    cards:
      - type: picture-entity
        entity: camera.octoprint
        camera_image: camera.octoprint
        show_state: false
        show_name: false
        aspect_ratio: 4x3
      - type: entities
        title: 3D tulostin
        show_header_toggle: false
        entities:
          - entity: switch.0x000d6ffffedaafbf_switch
            name: Virtakytkin
          - sensor.octoprint_current_state
          - sensor.octoprint_job_percentage
          - sensor.octoprint_time_elapsed_format
          - sensor.octoprint_time_remaining_format
          - type: divider
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_actual_tool0_temp

  - id: 4  # Automatically created id
    title: Piha
    type: vertical-stack
    cards:
      - id: 43406de7cd1f4f129ad6a89ab083cdb3  # Automatically created id
        type: picture-entity
        entity: camera.parkki
        camera_image: camera.parkki
        show_state: false
      - id: f24d163ee0d245ce90b4c9d40a52582c  # Automatically created id
        type: picture-entity
        entity: camera.talo
        camera_image: camera.talo
        show_state: false
      - id: fddc994c5f7a4924aca65a3f076ebb27  # Automatically created id
        type: entities
        title: Mittaus
        show_header_toggle: false
        entities:
          - sensor.ruuvitag_outdoor_temperature
          - sensor.ruuvitag_outdoor_humidity
      - id: 2feb1de222484885b495af3e49a7af41  # Automatically created id
        type: entities
        title: Katos
        show_header_toggle: false
        entities:
          - entity: switch.car_heater_side
            secondary_info: last-changed
          - sensor.garage_side_socket_power
          - input_boolean.car_heater_side_armed
          - input_datetime.car_heater_side_departure
      - id: 343308fb27034491aa6db427c9bd2b80  # Automatically created id
        type: entities
        title: Talli
        show_header_toggle: false
        entities:
          - entity: switch.car_heater_front
            secondary_info: last-changed
          - sensor.garage_front_socket_power
          - input_boolean.car_heater_front_armed
          - input_datetime.car_heater_front_departure
      - id: 0c3c88a2880a4715a132600ac0d4d274  # Automatically created id
        type: weather-forecast
        entity: weather.darksky
