homeassistant:
  latitude: !env_var HOME_LAT
  longitude: !env_var HOME_LONG
  elevation: 1
  unit_system: metric
  time_zone: Europe/Helsinki
  name: poyta16
  customize: !include customize.yaml
  
frontend:

mqtt:
  broker: mqtt
  port: 1883
  client_id: hass

sensor: !include sensors.yaml
