title: poyta16
views:
- name: Home
  type: vertical-stack
  cards:
  - type: entities
    title: Sensorit
    entities:
      - sensor.ruuvitag_indoor_temperature
      - sensor.ruuvitag_outdoor_temperature
      - sensor.ruuvitag_oven_temperature
      - sensor.ruuvitag_indoor_humidity
      - sensor.ruuvitag_outdoor_humidity
  - type: entities
    title: Ilmalämpöpumppu
    entities:
      - climate.toshiba_arctic_25
  - type: entities
    title: Kahvinkeitin
    entities:
      - sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_power
      - sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_current
      - sensor.philio_technology_corporation_pan11_smart_energy_plug_in_switch_energy
      - switch.philio_technology_corporation_pan11_smart_energy_plug_in_switch_switch